project_id = "ojstmxvlvrgwyquofuhb"

[functions.countdown-ticker]
verify_jwt = false

[functions.crusader-tts]
verify_jwt = false

[functions.game-lifecycle]
verify_jwt = false

[functions.mock-user-service]
verify_jwt = false

[functions.role-manager]
verify_jwt = false

[functions.paystack-deposit]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.paystack-withdraw]
verify_jwt = false

[functions.get-banks]
verify_jwt = false

[functions.verify-bank-account]
verify_jwt = false

[functions.expire-stale-deposits]
verify_jwt = false

[functions.verify-kyc]
verify_jwt = false

[functions.cycle-manager]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.send-transactional-email]
verify_jwt = false

[functions.livekit-token]
verify_jwt = false

[functions.cycle-status-check]
verify_jwt = false

[functions.elevenlabs-music]
verify_jwt = false
