project_id = "ojstmxvlvrgwyquofuhb"

[functions.crusader-tts]
verify_jwt = true

[functions.game-manager]
verify_jwt = true

[functions.game-timer]
verify_jwt = false

[functions.role-manager]
verify_jwt = true

[functions.paystack-deposit]
verify_jwt = true

[functions.paystack-webhook]
verify_jwt = false

[functions.paystack-withdraw]
verify_jwt = true

[functions.get-banks]
verify_jwt = false

[functions.verify-bank-account]
verify_jwt = true
