project_id = "ojstmxvlvrgwyquofuhb"

[functions.crusader-tts]
verify_jwt = true

[functions.game-manager]
verify_jwt = true

[functions.game-timer]
verify_jwt = false

[functions.role-manager]
verify_jwt = true